package com.cf.bootssm.dao;

import com.cf.bootssm.bean.CProject;
import java.util.List;

public interface CProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_project
     *
     * @mbg.generated
     */
    int insert(CProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_project
     *
     * @mbg.generated
     */
    CProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_project
     *
     * @mbg.generated
     */
    List<CProject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CProject record);
}